[package]
name = "rust-wasm-example"
version = "0.1.0"
authors = ["J. Ryan Stinnett <jryans@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
wasm-bindgen = "0.2"